apiVersion: v2
name: photoprism
home: https://photoprism.org/
description: A Photoprism Helm chart for Kubernetes
appVersion: "240711"
version: 1.3.1
sources:
- https://github.com/photoprism/photoprism